version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks: 
      - backend
  zap:
    image: "owasp/zap2docker-stable"
    ports:
      - "8080:8080"
    command: /bin/sh -c "zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.key=SupriseMotherFucker"
    networks:
      - backend
networks:
  backend:
